// flow-typed signature: f0c0eff190deadb5382c836e82fe601f
// flow-typed version: <<STUB>>/grumbler-scripts_v^2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grumbler-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grumbler-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grumbler-scripts/config/karma.conf' {
  declare module.exports: any;
}

declare module 'grumbler-scripts/config/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grumbler-scripts/config/karma.conf.js' {
  declare module.exports: $Exports<'grumbler-scripts/config/karma.conf'>;
}
declare module 'grumbler-scripts/config/webpack.config.js' {
  declare module.exports: $Exports<'grumbler-scripts/config/webpack.config'>;
}
